### ISSUE TITLE
SuperDialog be show in pager0 of HorizontalPager instead of current page or full screen

### ISSUE THREAD

**Issue by LiuYiGL** [miuix-kotlin-multiplatform/miuix#31]
When I use HorizontalPager to design my layout, found that SuperDialog be added in other page which always show in the first page.
At start, I think the Dialog is useless yet. 
Therefore, It has showed in first page when I use `NavigationBar` to turn to first page.
Version is 0.2.9.

These is my layout.
```kotlin
Column {
    HorizontalPager {
        Page0 {
             something()
        }
        Page1 {
            SuperDialog()
        }
    }
    NavigationBar{
        turn2Page0
        turn2Page1
    }
}
```

**Comment by YuKongA** [comment]
I can't reproduce this issue in the sample app. It seems to work fine.

**Comment by LiuYiGL** [comment]
Right, i get it.
it is reason that i dont use Scaffold component of miuix in other page.
this issue can close.
