### ISSUE TITLE
SuperDialog does not close 

### ISSUE THREAD

**Issue by chaikovskiy99** [miuix-kotlin-multiplatform/miuix#41]
I am trying to close super dialog on the press of "cancel" button by setting state to false in Modifier.clickable inside a column which is the container for the content, I can see the state changing. But dialog won't hide.

**Comment by YuKongA** [comment]
Need to use `dismissDialog(showDialog)` to close the SuperDialog.

```
    val showDialog = remember { mutableStateOf(false) }
    SuperDialog(
        title = "Dialog",
        summary = "Summary",
        show = showDialog,
        onDismissRequest = {
            dismissDialog(showDialog)
        }
    ) {
        TextButton(
            text = "Confirm",
            onClick = {
                dismissDialog(showDialog)
            },
            modifier = Modifier.weight(1f),
            colors = ButtonDefaults.textButtonColorsPrimary()
        )
    }
```

Example code: https://github.com/miuix-kotlin-multiplatform/miuix/blob/v0.3.0/composeApp/src/commonMain/kotlin/component/TextComponent.kt#L416

**Comment by chaikovskiy99** [comment]
Thanks for pointing out, it worked!
